model:
  default: deepseek-v4-flash
  provider: opencode-go
  base_url: https://opencode.ai/zen/go/v1
  api_mode: chat_completions
agent:
  max_turns: 150
  reasoning_effort: low
web:
  backend: ddgs
  use_gateway: false
auxiliary:
  vision:
    provider: opencode-go
    model: mimo-v2.5-pro
display:
  tool_progress: all
tts:
  use_gateway: false
gateway:
  platforms:
    api_server:
      enabled: false
_config_version: 33
platform_toolsets:
  cli:
  - browser
  - clarify
  - code_execution
  - cronjob
  - delegation
  - file
  - image_gen
  - memory
  - session_search
  - skills
  - terminal
  - todo
  - tts
  - vision
  - web
mcp_servers:
  context7:
    url: https://mcp.context7.com/mcp
    headers:
      Authorization: Bearer ctx7sk-2c7fa156-7263-4e9a-95ac-ef0417f28179
plugins:
  enabled:
  - platforms/a2a
  disabled: []
